# Initial Data Exploration

Nicholas Brusilow, 18 April 2026

This is a notebook for looking through the .csv files and just getting an idea for their shape and attributes

In [1]:
import os

import pandas as pd
import numpy as np

import duckdb

In [12]:
directory = '../original_csv'

extensions = ['.csv', '.CSV']

for file in os.listdir(directory):
    if file.endswith('.csv') or file.endswith('.CSV'):
        print(file)

Chase4122_Activity20260301_20260418_20260418.CSV
History-041826-083044.csv
History-041826-082650.csv

In [4]:
df = pd.read_csv('../original_csv/History-041826-082650.csv')

df.head()

,Date,Description,Amount,Balance,Post Date
0,02/18/2026,Mountain Mack Grosse PointeMI,$15.00,$0.00,02/19/2026
1,02/18/2026,Safeco Corporation Boston MA,$3042.00,$0.00,02/19/2026
2,02/19/2026,WESTBORN MARKET 43106 DEARBORN MI,$20.98,$0.00,02/20/2026
3,02/20/2026,SHELL OIL 57426569109 NEW BUFFALO MI,$18.69,$0.00,02/22/2026
4,02/20/2026,BP#3748563ANN ARBOR TRAV DEXTER MI,$33.97,$0.00,02/22/2026

In [2]:
df2 = pd.read_csv('../original_csv/History-041826-083044.csv')

df2.head()

,Date,Description,Amount,Balance
0,02/23/2026,DEPOSIT ONLINE BANKING TRANSFER FROM SHARE 01,$1000.00,$4320.30
1,02/25/2026,WITHDRAWAL ACH ALLIANT CU VISA TYPE: WEBSERVPM...,($3741.92),$578.38
2,02/27/2026,DEPOSIT ACH ST. JOHN THE BAP TYPE: PAYROLL ID:...,$1035.04,$1613.42
3,02/28/2026,DEPOSIT DIVIDEND Annual Percentage Yield Earne...,$0.78,$1614.20
4,03/10/2026,WITHDRAWAL ACH ALLIANT CU VISA TYPE: WEBSERVPM...,($441.41),$1172.79

In [6]:
df3 = pd.read_csv('../original_csv/Chase4122_Activity20260301_20260418_20260418.CSV')

df3.head()

,Transaction Date,Post Date,Description,Category,Type,Amount,Memo
0,04/10/2026,04/10/2026,Payment Thank You-Mobile,NaN,Payment,388.38,NaN
1,04/08/2026,04/09/2026,SP NAKED NUTRITION,Groceries,Sale,-98.99,NaN
2,04/08/2026,04/09/2026,IL TOLLWAY -PAY BY PLATE,Travel,Sale,-1.90,NaN
3,04/04/2026,04/06/2026,CONSUMER CELLULAR INC,Bills & Utilities,Sale,-86.15,NaN
4,04/03/2026,04/03/2026,AUTOMATIC PAYMENT - THANK,NaN,Payment,178.05,NaN

In [9]:
df3.Category

0                   NaN
1             Groceries
2                Travel
3     Bills & Utilities
4                   NaN
5     Health & Wellness
6                  Home
7                Travel
8                Travel
9             Education
10               Travel
11               Travel
12            Groceries
13    Health & Wellness
14    Bills & Utilities
15                 Home
16                  NaN
17               Travel
Name: Category, dtype: str